### ISSUE TITLE
Change to site_url context setting is not picked up

### ISSUE THREAD

**Issue by niciliketo** [modxcms/GoogleSiteMap#7]
1. View sitemap
2. change site_url in web context setting
3. Clear cache
4. View sitemap again
   NOTICE - sitemap.xml does not have the updated site_url

To fix this we temporarily commented the link in the snippet which checks the cache and re-enabled it once sitemap regenerated.
$output = $modx->cacheManager->get($cacheKey, $options); <--- Commented this line
if ($output !== null) return $output;

**Comment by pyrographics** [comment]
I can confirm this behavior.  Changing site_url isn't necessary, just forcing a different url with .htaccess causes it as well.  Clearing the MODX cache doesn't affect it.  I found that by changing the call to [[!GoogleSitemap? &itemTpl=`gItem`]] it works correctly.

**Comment by sepiariver** [comment]
@pyrographics @niciliketo Fixed in version 2.1.0-beta1  sorry for the long delay.
