### ISSUE TITLE
Default parameter values and caching

### ISSUE THREAD

**Issue by Jako** [modxcms/GoogleSiteMap#9]
The snippet seems to have issues with default parameter values and caching. I have to use explicit 
```
&context=`[[*context_key]]` &published=`1`
```
Otherwise some cached values from another context are used.

**Comment by sepiariver** [comment]
@Jako working on this for next release. Appreciate your input on these options:
1. Add context_key to cacheKey filename to prevent multi-context collisions
2. Use all scriptProperties variables, whether default or set, in the cacheKey hash.
Does option 2 seem like overkill? It's significantly more code than option 1...

**Comment by Jako** [comment]
Phew, 1. would be enough in most cases. 2. is better, since two snippet calls with some not default parameter values could be cached in the same cacheKey otherwise.

**Comment by Jako** [comment]
It looks like this issue is still valid: https://community.modx.com/t/sitemap-for-multi-domain/1124

**Comment by sepiariver** [comment]
Ok so there's this: 6a2cec7

Only thing is, it doesn't include the default parameters other than context. There's a balance here:

1. Include all default parameters, but then can only identify cache key after running all the parameter-setting logic, so there's a potential performance degradation for cache hits.
2. Leave it as it is in that commit, and other default parameters may cause cache collision.

What do you think? I could go either way. 1st option is more work, clearly. Maybe we iterate towards that? But I'm wondering if it's worth the performance issue. I haven't quantified the effect.
@Jako

**Comment by sepiariver** [comment]
released 2.1.1
